AvisFormation.WebUi/Controllers/AvisController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AvisFormation.Data;
using AvisFormation.Logic;
using AvisFormation.WebUi.Models;
using Microsoft.AspNet.Identity;

namespace AvisFormation.WebUi.Controllers
{
    public class AvisController : Controller
    {
        // GET: Avis
        [Authorize]
        public ActionResult LaisserUnAvis(string nomSeo)
        {
            var vm = new LaisserUnAvisViewModel();
            vm.NomSeo = nomSeo;
            using (var context = new AvisEntities())
            {
                var formationEntity = context.Formation.FirstOrDefault(f => f.NomSeo == nomSeo);

                if (formationEntity == null)
                    return RedirectToAction("Acceuil", "Home");

                vm.FormationName = formationEntity.Nom;
            }
            return View(vm);
        }

        [HttpPost]
        [Authorize]
        //public ActionResult SaveComment(string commentaire, string nom, string note, string nomSeo)
        public ActionResult SaveComment(SaveCommentViewModel comment)
        {
            using (var context = new AvisEntities())
            {
                var formationEntity = context.Formation.FirstOrDefault(f => f.NomSeo == comment.nomSeo);

                if (formationEntity == null)
                    return RedirectToAction("Acceuil", "Home");

                Avis nouvelAvis = new Avis();

                nouvelAvis.DateAvis = DateTime.Now;
                nouvelAvis.Description = comment.commentaire;

                nouvelAvis.UserId = User.Identity.GetUserId();

                var userId = User.Identity.GetUserId();

                var mgerUnicite = new UniqueAvisVerification();
                if(!mgerUnicite.EstAuthoriseACommenter(userId,formationEntity.Id))
                {
                    TempData["Message"] = "Désolé, vous ne pouvez poster qu'un seul avis par formation";
                    return RedirectToAction("DetailsFormation", "Formation", new { nomSeo = comment.nomSeo });
                }

                var mger = new PersonneManager();
                nouvelAvis.Nom = mger.GetNomFromUserId(userId);



                double dNote = 0;

                if(!double.TryParse(comment.note, NumberStyles.Any, CultureInfo.InvariantCulture, out dNote))
                {
                    throw new Exception("impossible de parser la note "+ comment.note);
                }
            
                nouvelAvis.Note = dNote;

                nouvelAvis.IdFormation = formationEntity.Id;
                context.Avis.Add(nouvelAvis);
                context.SaveChanges();
            }

            return RedirectToAction("DetailsFormation","Formation",new { nomSeo = comment.nomSeo });
        }
    }
}

AvisFormation.WebUi/Controllers/FormationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AvisFormation.Data;
using AvisFormation.WebUi.Models;

namespace AvisFormation.WebUi.Controllers
{
    public class FormationController : Controller
    {
        // GET: Formation
        public ActionResult ToutesLesFormations()
        {
            var vm = new AccueilViewModel();
            using (var context = new AvisEntities())
            {
                var listFormation = context.Formation.OrderBy(x => Guid.NewGuid()).ToList();
                foreach (var f in listFormation)
                {
                    var dto = new FormationAvecAvisDto();
                    dto.Formation = f;
                    if (f.Avis.Count == 0)
                        dto.Note = 0;
                    else
                        dto.Note = Math.Round(f.Avis.Average(a => a.Note), 2);
                    vm.ListFormations.Add(dto);
                }
            }
            return View(vm);
        }

        public ActionResult DetailsFormation(string nomSeo)
        {
            var vm = new FormationAvecAvisViewModel();
            using (var context = new AvisEntities())
            {
                var formationEntity = context.Formation.Where(f => f.NomSeo == nomSeo).FirstOrDefault();

                if (formationEntity == null)
                    return RedirectToAction("Accueil","Home");

                vm.FormationNom = formationEntity.Nom;
                vm.FormationDescription = formationEntity.Description;
                vm.FormationNomSeo = nomSeo;
                vm.FormationUrl = formationEntity.Url;
                if (formationEntity.Avis.Count > 0 )
                    vm.Note = formationEntity.Avis.Average(a => a.Note);
                vm.NombreAvis = formationEntity.Avis.Count;
                vm.Avis = formationEntity.Avis.OrderByDescending(a => a.DateAvis).ToList();
            }

            return View(vm);
        }
    }
}

AvisFormation.WebUi/Views/Formation/DetailsFormation.cshtml
@model AvisFormation.WebUi.Models.FormationAvecAvisViewModel
@{
    ViewBag.Title = Model.FormationNom;
}

<div class="container bg-white padding30">
    <h2>@Model.FormationNom</h2>

    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger">
            @TempData["Message"]
        </div>
    }

    <br />
    @Html.ActionLink("Laissez un avis sur cette formation", "LaisserUnAvis", "Avis", new { nomSeo = Model.FormationNomSeo }, new { @class = "big-link" })
    <p class="margin10"><b>@Model.FormationDescription</b></p>

    @foreach (var avis in Model.Avis)
    {
        <article class="bg-grey avis">
            <div>
                <i>@avis.Nom</i>
                <span class="left-margin">
                    @for (var i = 0; i < avis.Note; i++)
                    {
                        <span class="glyphicon glyphicon-star orange"></span>
                    }
                </span>
            </div>

            <br />
            <div>@avis.Description</div>
        </article>
        <br />
    }

</div>

AvisFormation.WebUi/Views/Formation/ToutesLesFormations.cshtml
@model AvisFormation.WebUi.Models.AccueilViewModel

@{
    ViewBag.Title = "Toutes les formations";
}
<div class="container bg-white padding30">

    <h2>Toutes les formations</h2>

    <div class="container text-center">
        @foreach (var dto in Model.ListFormations)
        {
            @Html.Partial("TuileFormation",dto)
        }
    </div>

    @*
        @foreach (var formation in Model)
        {
            <div><span>Nom :</span><span>@formation.Nom</span></div>
            <div><span>Description :</span><span>@formation.Description</span></div>
            <div>formation.NomSeo</div>
            <div>@formation.NomSeo</div>
        }
    *@
</div>